name       : dleyna-connector-dbus
version    : 0.2.0
release    : 1
source     :
    - https://01.org/sites/default/files/downloads/dleyna/dleyna-connector-dbus-0.2.0.tar.gz : e791511206761282a658bb8253de076dcb1f8c8fbdc81219efe5ffe80cb2bea5
license    : LGPL-2.1
summary    : D-Bus API for the dLeyna services
description: |
    D-Bus API for the dLeyna services
builddeps  :
    - pkgconfig(dbus-1)
    - pkgconfig(dleyna-core-1.0)
    - pkgconfig(gio-2.0)
    - pkgconfig(glib-2.0)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
